### ISSUE TITLE
client.ovpn not being created on local/host enviournment

### ISSUE THREAD

**Issue by ghost** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#7] opened 2021-06-06 19:42 UTC
Hey, great job on the script! Even though I'm using Azure for this, I gave it a try on my VM Ubuntu and I have an issue to report.

Issue: After selecting the option to continue with local/host configuration in the initial setup, no client.ovpn file is created.
I've tried downloading from the IP, going to the root folder with cat /root/client.ovpn but no file is found.

Please have a look at this as it might help others. 

Specifications: Ubuntu LTS 20.04.02 running on Oracle VM Virtual Box

I have another issue () regarding the matchmaking not working, I would appreciate if you could look into it too <3.

**Comment by fswdevl** [comment] 2021-06-06 20:52
If you ran the setup as root then it will be /root/client.ovpn otherwise it will be in the home folder of the USER you ran as.

**Closed** 2021-06-12 21:38 UTC

**Comment by fabricemasachs** [comment] 2021-07-02 12:52
I faced the same issue after installed "Ubuntu 20.04.2.0 desktop" and the problem is curl not being installed!!!

- First update the system and get latest stable curl version for Ubuntu:
`sudo apt update`
`sudo apt upgrade`

- Install cURL
`sudo apt install curl`

- Then start the initial setup
`sudo bash d2firewall.sh -a setup`

As @fswdevl said your client.ovpn will be in the home folder of the USER you ran as.

@fswdevl It will be nice to add a check for this dependency in the bash before installing OpenVPN.
